@startuml transfer
    actor User1
    actor User2
    User1 -> "backend" : transfer(sender_id, receiver_id, amount, password)
    "backend" -> "MySQL" : getPassword(user_id)
    "MySQL" -> "backend" : return password
    "backend" -> "backend" : check if password is correct
    alt (password is not correct)
    "backend" -> User1 : Transfer failed, wrong password
    else (password is correct)

    
    "backend" -> "MySQL": start Transaction
    activate "MySQL" #005500
    "backend" -> "MySQL" : getBalance(sender_id)
    "MySQL" -> "backend" : return balance
    "backend" -> "backend" : check if balance >= amount
    alt (balance < amount)
    "backend" -> User1 : does not save enough money
   
    else (balance >= amount)
    "backend" -> "MySQL" : minusBalance(sender_id, amount)
   
    "backend" -> "MySQL" : plusBalance(receiver_id, amount)
   
    "backend" -> "MySQL" : create transfer certificate
    
    "backend" -> "MySQL" : create history for sender
    
    "backend" -> "MySQL" : create history for receiver

    "backend" -> "MySQL" : create notification for receiver
    
    "backend" -> "MySQL" : getBalance(sender_id)
    "MySQL" -> "backend" : return balance
    "backend" -> "MySQL" : commit
    deactivate "MySQL"
    "backend" -> User1 : return OK + balance + history
    "backend" -> User2 : send notification
    end
    end
@enduml