// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintech.proto

package vn.zalopay.ducnm8.grpc;

public interface BalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fintech.BalanceRequest)
    com.google.protobuf.MessageOrBuilder {
}
