// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintech.proto

package vn.zalopay.ducnm8.grpc;

/**
 * Protobuf type {@code fintech.HistoryItem}
 */
public  final class HistoryItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintech.HistoryItem)
    HistoryItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HistoryItem.newBuilder() to construct.
  private HistoryItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HistoryItem() {
    historyId_ = 0L;
    partnerId_ = 0L;
    partnerUsername_ = "";
    partnerFullname_ = "";
    amount_ = 0L;
    message_ = "";
    timestamp_ = 0L;
    balance_ = 0L;
    transferType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HistoryItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            historyId_ = input.readInt64();
            break;
          }
          case 16: {

            partnerId_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            partnerUsername_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            partnerFullname_ = s;
            break;
          }
          case 40: {

            amount_ = input.readInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 56: {

            timestamp_ = input.readInt64();
            break;
          }
          case 64: {

            balance_ = input.readInt64();
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            transferType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryItem_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vn.zalopay.ducnm8.grpc.HistoryItem.class, vn.zalopay.ducnm8.grpc.HistoryItem.Builder.class);
  }

  /**
   * Protobuf enum {@code fintech.HistoryItem.TransferType}
   */
  public enum TransferType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SEND = 0;</code>
     */
    SEND(0),
    /**
     * <code>RECEIVE = 1;</code>
     */
    RECEIVE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SEND = 0;</code>
     */
    public static final int SEND_VALUE = 0;
    /**
     * <code>RECEIVE = 1;</code>
     */
    public static final int RECEIVE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TransferType valueOf(int value) {
      return forNumber(value);
    }

    public static TransferType forNumber(int value) {
      switch (value) {
        case 0: return SEND;
        case 1: return RECEIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransferType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TransferType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransferType>() {
            public TransferType findValueByNumber(int number) {
              return TransferType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return vn.zalopay.ducnm8.grpc.HistoryItem.getDescriptor().getEnumTypes().get(0);
    }

    private static final TransferType[] VALUES = values();

    public static TransferType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TransferType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fintech.HistoryItem.TransferType)
  }

  public static final int HISTORY_ID_FIELD_NUMBER = 1;
  private long historyId_;
  /**
   * <pre>
   * Information of a user transfer money with it's partner
   * This hisotry has an enum TransferType
   * If TransferType = SEND =&gt; user send money to partner
   * If TransferType = RECEIVE =&gt; user receive money from partner
   * </pre>
   *
   * <code>int64 history_id = 1;</code>
   */
  public long getHistoryId() {
    return historyId_;
  }

  public static final int PARTNER_ID_FIELD_NUMBER = 2;
  private long partnerId_;
  /**
   * <code>int64 partner_id = 2;</code>
   */
  public long getPartnerId() {
    return partnerId_;
  }

  public static final int PARTNER_USERNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object partnerUsername_;
  /**
   * <code>string partner_username = 3;</code>
   */
  public java.lang.String getPartnerUsername() {
    java.lang.Object ref = partnerUsername_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partnerUsername_ = s;
      return s;
    }
  }
  /**
   * <code>string partner_username = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPartnerUsernameBytes() {
    java.lang.Object ref = partnerUsername_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partnerUsername_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTNER_FULLNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object partnerFullname_;
  /**
   * <code>string partner_fullname = 4;</code>
   */
  public java.lang.String getPartnerFullname() {
    java.lang.Object ref = partnerFullname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partnerFullname_ = s;
      return s;
    }
  }
  /**
   * <code>string partner_fullname = 4;</code>
   */
  public com.google.protobuf.ByteString
      getPartnerFullnameBytes() {
    java.lang.Object ref = partnerFullname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partnerFullname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 5;
  private long amount_;
  /**
   * <code>int64 amount = 5;</code>
   */
  public long getAmount() {
    return amount_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 6;
  private volatile java.lang.Object message_;
  /**
   * <pre>
   * The message goes with a transfer
   * </pre>
   *
   * <code>string message = 6;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The message goes with a transfer
   * </pre>
   *
   * <code>string message = 6;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_;
  /**
   * <pre>
   * The time when the transfer executed
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int BALANCE_FIELD_NUMBER = 8;
  private long balance_;
  /**
   * <pre>
   * The balance of user after transfer
   * </pre>
   *
   * <code>int64 balance = 8;</code>
   */
  public long getBalance() {
    return balance_;
  }

  public static final int TRANSFER_TYPE_FIELD_NUMBER = 9;
  private int transferType_;
  /**
   * <code>.fintech.HistoryItem.TransferType transfer_type = 9;</code>
   */
  public int getTransferTypeValue() {
    return transferType_;
  }
  /**
   * <code>.fintech.HistoryItem.TransferType transfer_type = 9;</code>
   */
  public vn.zalopay.ducnm8.grpc.HistoryItem.TransferType getTransferType() {
    vn.zalopay.ducnm8.grpc.HistoryItem.TransferType result = vn.zalopay.ducnm8.grpc.HistoryItem.TransferType.valueOf(transferType_);
    return result == null ? vn.zalopay.ducnm8.grpc.HistoryItem.TransferType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (historyId_ != 0L) {
      output.writeInt64(1, historyId_);
    }
    if (partnerId_ != 0L) {
      output.writeInt64(2, partnerId_);
    }
    if (!getPartnerUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, partnerUsername_);
    }
    if (!getPartnerFullnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, partnerFullname_);
    }
    if (amount_ != 0L) {
      output.writeInt64(5, amount_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, message_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    if (balance_ != 0L) {
      output.writeInt64(8, balance_);
    }
    if (transferType_ != vn.zalopay.ducnm8.grpc.HistoryItem.TransferType.SEND.getNumber()) {
      output.writeEnum(9, transferType_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (historyId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, historyId_);
    }
    if (partnerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, partnerId_);
    }
    if (!getPartnerUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, partnerUsername_);
    }
    if (!getPartnerFullnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, partnerFullname_);
    }
    if (amount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, amount_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, message_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    if (balance_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, balance_);
    }
    if (transferType_ != vn.zalopay.ducnm8.grpc.HistoryItem.TransferType.SEND.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, transferType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vn.zalopay.ducnm8.grpc.HistoryItem)) {
      return super.equals(obj);
    }
    vn.zalopay.ducnm8.grpc.HistoryItem other = (vn.zalopay.ducnm8.grpc.HistoryItem) obj;

    boolean result = true;
    result = result && (getHistoryId()
        == other.getHistoryId());
    result = result && (getPartnerId()
        == other.getPartnerId());
    result = result && getPartnerUsername()
        .equals(other.getPartnerUsername());
    result = result && getPartnerFullname()
        .equals(other.getPartnerFullname());
    result = result && (getAmount()
        == other.getAmount());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && (getBalance()
        == other.getBalance());
    result = result && transferType_ == other.transferType_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HISTORY_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHistoryId());
    hash = (37 * hash) + PARTNER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPartnerId());
    hash = (37 * hash) + PARTNER_USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPartnerUsername().hashCode();
    hash = (37 * hash) + PARTNER_FULLNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPartnerFullname().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmount());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + BALANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBalance());
    hash = (37 * hash) + TRANSFER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + transferType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vn.zalopay.ducnm8.grpc.HistoryItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vn.zalopay.ducnm8.grpc.HistoryItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fintech.HistoryItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintech.HistoryItem)
      vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vn.zalopay.ducnm8.grpc.HistoryItem.class, vn.zalopay.ducnm8.grpc.HistoryItem.Builder.class);
    }

    // Construct using vn.zalopay.ducnm8.grpc.HistoryItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      historyId_ = 0L;

      partnerId_ = 0L;

      partnerUsername_ = "";

      partnerFullname_ = "";

      amount_ = 0L;

      message_ = "";

      timestamp_ = 0L;

      balance_ = 0L;

      transferType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryItem_descriptor;
    }

    public vn.zalopay.ducnm8.grpc.HistoryItem getDefaultInstanceForType() {
      return vn.zalopay.ducnm8.grpc.HistoryItem.getDefaultInstance();
    }

    public vn.zalopay.ducnm8.grpc.HistoryItem build() {
      vn.zalopay.ducnm8.grpc.HistoryItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public vn.zalopay.ducnm8.grpc.HistoryItem buildPartial() {
      vn.zalopay.ducnm8.grpc.HistoryItem result = new vn.zalopay.ducnm8.grpc.HistoryItem(this);
      result.historyId_ = historyId_;
      result.partnerId_ = partnerId_;
      result.partnerUsername_ = partnerUsername_;
      result.partnerFullname_ = partnerFullname_;
      result.amount_ = amount_;
      result.message_ = message_;
      result.timestamp_ = timestamp_;
      result.balance_ = balance_;
      result.transferType_ = transferType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vn.zalopay.ducnm8.grpc.HistoryItem) {
        return mergeFrom((vn.zalopay.ducnm8.grpc.HistoryItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vn.zalopay.ducnm8.grpc.HistoryItem other) {
      if (other == vn.zalopay.ducnm8.grpc.HistoryItem.getDefaultInstance()) return this;
      if (other.getHistoryId() != 0L) {
        setHistoryId(other.getHistoryId());
      }
      if (other.getPartnerId() != 0L) {
        setPartnerId(other.getPartnerId());
      }
      if (!other.getPartnerUsername().isEmpty()) {
        partnerUsername_ = other.partnerUsername_;
        onChanged();
      }
      if (!other.getPartnerFullname().isEmpty()) {
        partnerFullname_ = other.partnerFullname_;
        onChanged();
      }
      if (other.getAmount() != 0L) {
        setAmount(other.getAmount());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getBalance() != 0L) {
        setBalance(other.getBalance());
      }
      if (other.transferType_ != 0) {
        setTransferTypeValue(other.getTransferTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      vn.zalopay.ducnm8.grpc.HistoryItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (vn.zalopay.ducnm8.grpc.HistoryItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long historyId_ ;
    /**
     * <pre>
     * Information of a user transfer money with it's partner
     * This hisotry has an enum TransferType
     * If TransferType = SEND =&gt; user send money to partner
     * If TransferType = RECEIVE =&gt; user receive money from partner
     * </pre>
     *
     * <code>int64 history_id = 1;</code>
     */
    public long getHistoryId() {
      return historyId_;
    }
    /**
     * <pre>
     * Information of a user transfer money with it's partner
     * This hisotry has an enum TransferType
     * If TransferType = SEND =&gt; user send money to partner
     * If TransferType = RECEIVE =&gt; user receive money from partner
     * </pre>
     *
     * <code>int64 history_id = 1;</code>
     */
    public Builder setHistoryId(long value) {
      
      historyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Information of a user transfer money with it's partner
     * This hisotry has an enum TransferType
     * If TransferType = SEND =&gt; user send money to partner
     * If TransferType = RECEIVE =&gt; user receive money from partner
     * </pre>
     *
     * <code>int64 history_id = 1;</code>
     */
    public Builder clearHistoryId() {
      
      historyId_ = 0L;
      onChanged();
      return this;
    }

    private long partnerId_ ;
    /**
     * <code>int64 partner_id = 2;</code>
     */
    public long getPartnerId() {
      return partnerId_;
    }
    /**
     * <code>int64 partner_id = 2;</code>
     */
    public Builder setPartnerId(long value) {
      
      partnerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 partner_id = 2;</code>
     */
    public Builder clearPartnerId() {
      
      partnerId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object partnerUsername_ = "";
    /**
     * <code>string partner_username = 3;</code>
     */
    public java.lang.String getPartnerUsername() {
      java.lang.Object ref = partnerUsername_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partnerUsername_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string partner_username = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPartnerUsernameBytes() {
      java.lang.Object ref = partnerUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partnerUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string partner_username = 3;</code>
     */
    public Builder setPartnerUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      partnerUsername_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string partner_username = 3;</code>
     */
    public Builder clearPartnerUsername() {
      
      partnerUsername_ = getDefaultInstance().getPartnerUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string partner_username = 3;</code>
     */
    public Builder setPartnerUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      partnerUsername_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object partnerFullname_ = "";
    /**
     * <code>string partner_fullname = 4;</code>
     */
    public java.lang.String getPartnerFullname() {
      java.lang.Object ref = partnerFullname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partnerFullname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string partner_fullname = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPartnerFullnameBytes() {
      java.lang.Object ref = partnerFullname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partnerFullname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string partner_fullname = 4;</code>
     */
    public Builder setPartnerFullname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      partnerFullname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string partner_fullname = 4;</code>
     */
    public Builder clearPartnerFullname() {
      
      partnerFullname_ = getDefaultInstance().getPartnerFullname();
      onChanged();
      return this;
    }
    /**
     * <code>string partner_fullname = 4;</code>
     */
    public Builder setPartnerFullnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      partnerFullname_ = value;
      onChanged();
      return this;
    }

    private long amount_ ;
    /**
     * <code>int64 amount = 5;</code>
     */
    public long getAmount() {
      return amount_;
    }
    /**
     * <code>int64 amount = 5;</code>
     */
    public Builder setAmount(long value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 amount = 5;</code>
     */
    public Builder clearAmount() {
      
      amount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * The message goes with a transfer
     * </pre>
     *
     * <code>string message = 6;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The message goes with a transfer
     * </pre>
     *
     * <code>string message = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The message goes with a transfer
     * </pre>
     *
     * <code>string message = 6;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The message goes with a transfer
     * </pre>
     *
     * <code>string message = 6;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The message goes with a transfer
     * </pre>
     *
     * <code>string message = 6;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * The time when the transfer executed
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * The time when the transfer executed
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The time when the transfer executed
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private long balance_ ;
    /**
     * <pre>
     * The balance of user after transfer
     * </pre>
     *
     * <code>int64 balance = 8;</code>
     */
    public long getBalance() {
      return balance_;
    }
    /**
     * <pre>
     * The balance of user after transfer
     * </pre>
     *
     * <code>int64 balance = 8;</code>
     */
    public Builder setBalance(long value) {
      
      balance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The balance of user after transfer
     * </pre>
     *
     * <code>int64 balance = 8;</code>
     */
    public Builder clearBalance() {
      
      balance_ = 0L;
      onChanged();
      return this;
    }

    private int transferType_ = 0;
    /**
     * <code>.fintech.HistoryItem.TransferType transfer_type = 9;</code>
     */
    public int getTransferTypeValue() {
      return transferType_;
    }
    /**
     * <code>.fintech.HistoryItem.TransferType transfer_type = 9;</code>
     */
    public Builder setTransferTypeValue(int value) {
      transferType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.fintech.HistoryItem.TransferType transfer_type = 9;</code>
     */
    public vn.zalopay.ducnm8.grpc.HistoryItem.TransferType getTransferType() {
      vn.zalopay.ducnm8.grpc.HistoryItem.TransferType result = vn.zalopay.ducnm8.grpc.HistoryItem.TransferType.valueOf(transferType_);
      return result == null ? vn.zalopay.ducnm8.grpc.HistoryItem.TransferType.UNRECOGNIZED : result;
    }
    /**
     * <code>.fintech.HistoryItem.TransferType transfer_type = 9;</code>
     */
    public Builder setTransferType(vn.zalopay.ducnm8.grpc.HistoryItem.TransferType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      transferType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.fintech.HistoryItem.TransferType transfer_type = 9;</code>
     */
    public Builder clearTransferType() {
      
      transferType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintech.HistoryItem)
  }

  // @@protoc_insertion_point(class_scope:fintech.HistoryItem)
  private static final vn.zalopay.ducnm8.grpc.HistoryItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vn.zalopay.ducnm8.grpc.HistoryItem();
  }

  public static vn.zalopay.ducnm8.grpc.HistoryItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HistoryItem>
      PARSER = new com.google.protobuf.AbstractParser<HistoryItem>() {
    public HistoryItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new HistoryItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HistoryItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HistoryItem> getParserForType() {
    return PARSER;
  }

  public vn.zalopay.ducnm8.grpc.HistoryItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

