// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintech.proto

package vn.zalopay.ducnm8.grpc;

/**
 * Protobuf type {@code fintech.HistoryResponse}
 */
public  final class HistoryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintech.HistoryResponse)
    HistoryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HistoryResponse.newBuilder() to construct.
  private HistoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HistoryResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HistoryResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            vn.zalopay.ducnm8.grpc.Error.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(vn.zalopay.ducnm8.grpc.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            vn.zalopay.ducnm8.grpc.HistoryResponse.Data.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(vn.zalopay.ducnm8.grpc.HistoryResponse.Data.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vn.zalopay.ducnm8.grpc.HistoryResponse.class, vn.zalopay.ducnm8.grpc.HistoryResponse.Builder.class);
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fintech.HistoryResponse.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Contain a list of transfer history of a user
     * Need jwt token authentication to call
     * user_id is taken from jwt token
     * </pre>
     *
     * <code>repeated .fintech.HistoryItem history_items = 1;</code>
     */
    java.util.List<vn.zalopay.ducnm8.grpc.HistoryItem> 
        getHistoryItemsList();
    /**
     * <pre>
     * Contain a list of transfer history of a user
     * Need jwt token authentication to call
     * user_id is taken from jwt token
     * </pre>
     *
     * <code>repeated .fintech.HistoryItem history_items = 1;</code>
     */
    vn.zalopay.ducnm8.grpc.HistoryItem getHistoryItems(int index);
    /**
     * <pre>
     * Contain a list of transfer history of a user
     * Need jwt token authentication to call
     * user_id is taken from jwt token
     * </pre>
     *
     * <code>repeated .fintech.HistoryItem history_items = 1;</code>
     */
    int getHistoryItemsCount();
    /**
     * <pre>
     * Contain a list of transfer history of a user
     * Need jwt token authentication to call
     * user_id is taken from jwt token
     * </pre>
     *
     * <code>repeated .fintech.HistoryItem history_items = 1;</code>
     */
    java.util.List<? extends vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder> 
        getHistoryItemsOrBuilderList();
    /**
     * <pre>
     * Contain a list of transfer history of a user
     * Need jwt token authentication to call
     * user_id is taken from jwt token
     * </pre>
     *
     * <code>repeated .fintech.HistoryItem history_items = 1;</code>
     */
    vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder getHistoryItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code fintech.HistoryResponse.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fintech.HistoryResponse.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      historyItems_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                historyItems_ = new java.util.ArrayList<vn.zalopay.ducnm8.grpc.HistoryItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              historyItems_.add(
                  input.readMessage(vn.zalopay.ducnm8.grpc.HistoryItem.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          historyItems_ = java.util.Collections.unmodifiableList(historyItems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryResponse_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryResponse_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vn.zalopay.ducnm8.grpc.HistoryResponse.Data.class, vn.zalopay.ducnm8.grpc.HistoryResponse.Data.Builder.class);
    }

    public static final int HISTORY_ITEMS_FIELD_NUMBER = 1;
    private java.util.List<vn.zalopay.ducnm8.grpc.HistoryItem> historyItems_;
    /**
     * <pre>
     * Contain a list of transfer history of a user
     * Need jwt token authentication to call
     * user_id is taken from jwt token
     * </pre>
     *
     * <code>repeated .fintech.HistoryItem history_items = 1;</code>
     */
    public java.util.List<vn.zalopay.ducnm8.grpc.HistoryItem> getHistoryItemsList() {
      return historyItems_;
    }
    /**
     * <pre>
     * Contain a list of transfer history of a user
     * Need jwt token authentication to call
     * user_id is taken from jwt token
     * </pre>
     *
     * <code>repeated .fintech.HistoryItem history_items = 1;</code>
     */
    public java.util.List<? extends vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder> 
        getHistoryItemsOrBuilderList() {
      return historyItems_;
    }
    /**
     * <pre>
     * Contain a list of transfer history of a user
     * Need jwt token authentication to call
     * user_id is taken from jwt token
     * </pre>
     *
     * <code>repeated .fintech.HistoryItem history_items = 1;</code>
     */
    public int getHistoryItemsCount() {
      return historyItems_.size();
    }
    /**
     * <pre>
     * Contain a list of transfer history of a user
     * Need jwt token authentication to call
     * user_id is taken from jwt token
     * </pre>
     *
     * <code>repeated .fintech.HistoryItem history_items = 1;</code>
     */
    public vn.zalopay.ducnm8.grpc.HistoryItem getHistoryItems(int index) {
      return historyItems_.get(index);
    }
    /**
     * <pre>
     * Contain a list of transfer history of a user
     * Need jwt token authentication to call
     * user_id is taken from jwt token
     * </pre>
     *
     * <code>repeated .fintech.HistoryItem history_items = 1;</code>
     */
    public vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder getHistoryItemsOrBuilder(
        int index) {
      return historyItems_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < historyItems_.size(); i++) {
        output.writeMessage(1, historyItems_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < historyItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, historyItems_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vn.zalopay.ducnm8.grpc.HistoryResponse.Data)) {
        return super.equals(obj);
      }
      vn.zalopay.ducnm8.grpc.HistoryResponse.Data other = (vn.zalopay.ducnm8.grpc.HistoryResponse.Data) obj;

      boolean result = true;
      result = result && getHistoryItemsList()
          .equals(other.getHistoryItemsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHistoryItemsCount() > 0) {
        hash = (37 * hash) + HISTORY_ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getHistoryItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vn.zalopay.ducnm8.grpc.HistoryResponse.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fintech.HistoryResponse.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fintech.HistoryResponse.Data)
        vn.zalopay.ducnm8.grpc.HistoryResponse.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryResponse_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryResponse_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vn.zalopay.ducnm8.grpc.HistoryResponse.Data.class, vn.zalopay.ducnm8.grpc.HistoryResponse.Data.Builder.class);
      }

      // Construct using vn.zalopay.ducnm8.grpc.HistoryResponse.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHistoryItemsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (historyItemsBuilder_ == null) {
          historyItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          historyItemsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryResponse_Data_descriptor;
      }

      public vn.zalopay.ducnm8.grpc.HistoryResponse.Data getDefaultInstanceForType() {
        return vn.zalopay.ducnm8.grpc.HistoryResponse.Data.getDefaultInstance();
      }

      public vn.zalopay.ducnm8.grpc.HistoryResponse.Data build() {
        vn.zalopay.ducnm8.grpc.HistoryResponse.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public vn.zalopay.ducnm8.grpc.HistoryResponse.Data buildPartial() {
        vn.zalopay.ducnm8.grpc.HistoryResponse.Data result = new vn.zalopay.ducnm8.grpc.HistoryResponse.Data(this);
        int from_bitField0_ = bitField0_;
        if (historyItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            historyItems_ = java.util.Collections.unmodifiableList(historyItems_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.historyItems_ = historyItems_;
        } else {
          result.historyItems_ = historyItemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vn.zalopay.ducnm8.grpc.HistoryResponse.Data) {
          return mergeFrom((vn.zalopay.ducnm8.grpc.HistoryResponse.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vn.zalopay.ducnm8.grpc.HistoryResponse.Data other) {
        if (other == vn.zalopay.ducnm8.grpc.HistoryResponse.Data.getDefaultInstance()) return this;
        if (historyItemsBuilder_ == null) {
          if (!other.historyItems_.isEmpty()) {
            if (historyItems_.isEmpty()) {
              historyItems_ = other.historyItems_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHistoryItemsIsMutable();
              historyItems_.addAll(other.historyItems_);
            }
            onChanged();
          }
        } else {
          if (!other.historyItems_.isEmpty()) {
            if (historyItemsBuilder_.isEmpty()) {
              historyItemsBuilder_.dispose();
              historyItemsBuilder_ = null;
              historyItems_ = other.historyItems_;
              bitField0_ = (bitField0_ & ~0x00000001);
              historyItemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHistoryItemsFieldBuilder() : null;
            } else {
              historyItemsBuilder_.addAllMessages(other.historyItems_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vn.zalopay.ducnm8.grpc.HistoryResponse.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vn.zalopay.ducnm8.grpc.HistoryResponse.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<vn.zalopay.ducnm8.grpc.HistoryItem> historyItems_ =
        java.util.Collections.emptyList();
      private void ensureHistoryItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          historyItems_ = new java.util.ArrayList<vn.zalopay.ducnm8.grpc.HistoryItem>(historyItems_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          vn.zalopay.ducnm8.grpc.HistoryItem, vn.zalopay.ducnm8.grpc.HistoryItem.Builder, vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder> historyItemsBuilder_;

      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public java.util.List<vn.zalopay.ducnm8.grpc.HistoryItem> getHistoryItemsList() {
        if (historyItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(historyItems_);
        } else {
          return historyItemsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public int getHistoryItemsCount() {
        if (historyItemsBuilder_ == null) {
          return historyItems_.size();
        } else {
          return historyItemsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public vn.zalopay.ducnm8.grpc.HistoryItem getHistoryItems(int index) {
        if (historyItemsBuilder_ == null) {
          return historyItems_.get(index);
        } else {
          return historyItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public Builder setHistoryItems(
          int index, vn.zalopay.ducnm8.grpc.HistoryItem value) {
        if (historyItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHistoryItemsIsMutable();
          historyItems_.set(index, value);
          onChanged();
        } else {
          historyItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public Builder setHistoryItems(
          int index, vn.zalopay.ducnm8.grpc.HistoryItem.Builder builderForValue) {
        if (historyItemsBuilder_ == null) {
          ensureHistoryItemsIsMutable();
          historyItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          historyItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public Builder addHistoryItems(vn.zalopay.ducnm8.grpc.HistoryItem value) {
        if (historyItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHistoryItemsIsMutable();
          historyItems_.add(value);
          onChanged();
        } else {
          historyItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public Builder addHistoryItems(
          int index, vn.zalopay.ducnm8.grpc.HistoryItem value) {
        if (historyItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHistoryItemsIsMutable();
          historyItems_.add(index, value);
          onChanged();
        } else {
          historyItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public Builder addHistoryItems(
          vn.zalopay.ducnm8.grpc.HistoryItem.Builder builderForValue) {
        if (historyItemsBuilder_ == null) {
          ensureHistoryItemsIsMutable();
          historyItems_.add(builderForValue.build());
          onChanged();
        } else {
          historyItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public Builder addHistoryItems(
          int index, vn.zalopay.ducnm8.grpc.HistoryItem.Builder builderForValue) {
        if (historyItemsBuilder_ == null) {
          ensureHistoryItemsIsMutable();
          historyItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          historyItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public Builder addAllHistoryItems(
          java.lang.Iterable<? extends vn.zalopay.ducnm8.grpc.HistoryItem> values) {
        if (historyItemsBuilder_ == null) {
          ensureHistoryItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, historyItems_);
          onChanged();
        } else {
          historyItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public Builder clearHistoryItems() {
        if (historyItemsBuilder_ == null) {
          historyItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          historyItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public Builder removeHistoryItems(int index) {
        if (historyItemsBuilder_ == null) {
          ensureHistoryItemsIsMutable();
          historyItems_.remove(index);
          onChanged();
        } else {
          historyItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public vn.zalopay.ducnm8.grpc.HistoryItem.Builder getHistoryItemsBuilder(
          int index) {
        return getHistoryItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder getHistoryItemsOrBuilder(
          int index) {
        if (historyItemsBuilder_ == null) {
          return historyItems_.get(index);  } else {
          return historyItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public java.util.List<? extends vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder> 
           getHistoryItemsOrBuilderList() {
        if (historyItemsBuilder_ != null) {
          return historyItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(historyItems_);
        }
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public vn.zalopay.ducnm8.grpc.HistoryItem.Builder addHistoryItemsBuilder() {
        return getHistoryItemsFieldBuilder().addBuilder(
            vn.zalopay.ducnm8.grpc.HistoryItem.getDefaultInstance());
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public vn.zalopay.ducnm8.grpc.HistoryItem.Builder addHistoryItemsBuilder(
          int index) {
        return getHistoryItemsFieldBuilder().addBuilder(
            index, vn.zalopay.ducnm8.grpc.HistoryItem.getDefaultInstance());
      }
      /**
       * <pre>
       * Contain a list of transfer history of a user
       * Need jwt token authentication to call
       * user_id is taken from jwt token
       * </pre>
       *
       * <code>repeated .fintech.HistoryItem history_items = 1;</code>
       */
      public java.util.List<vn.zalopay.ducnm8.grpc.HistoryItem.Builder> 
           getHistoryItemsBuilderList() {
        return getHistoryItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          vn.zalopay.ducnm8.grpc.HistoryItem, vn.zalopay.ducnm8.grpc.HistoryItem.Builder, vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder> 
          getHistoryItemsFieldBuilder() {
        if (historyItemsBuilder_ == null) {
          historyItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              vn.zalopay.ducnm8.grpc.HistoryItem, vn.zalopay.ducnm8.grpc.HistoryItem.Builder, vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder>(
                  historyItems_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          historyItems_ = null;
        }
        return historyItemsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fintech.HistoryResponse.Data)
    }

    // @@protoc_insertion_point(class_scope:fintech.HistoryResponse.Data)
    private static final vn.zalopay.ducnm8.grpc.HistoryResponse.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vn.zalopay.ducnm8.grpc.HistoryResponse.Data();
    }

    public static vn.zalopay.ducnm8.grpc.HistoryResponse.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    public vn.zalopay.ducnm8.grpc.HistoryResponse.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ERROR_FIELD_NUMBER = 1;
  private vn.zalopay.ducnm8.grpc.Error error_;
  /**
   * <code>.fintech.Error error = 1;</code>
   */
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.fintech.Error error = 1;</code>
   */
  public vn.zalopay.ducnm8.grpc.Error getError() {
    return error_ == null ? vn.zalopay.ducnm8.grpc.Error.getDefaultInstance() : error_;
  }
  /**
   * <code>.fintech.Error error = 1;</code>
   */
  public vn.zalopay.ducnm8.grpc.ErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private vn.zalopay.ducnm8.grpc.HistoryResponse.Data data_;
  /**
   * <code>.fintech.HistoryResponse.Data data = 2;</code>
   */
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.fintech.HistoryResponse.Data data = 2;</code>
   */
  public vn.zalopay.ducnm8.grpc.HistoryResponse.Data getData() {
    return data_ == null ? vn.zalopay.ducnm8.grpc.HistoryResponse.Data.getDefaultInstance() : data_;
  }
  /**
   * <code>.fintech.HistoryResponse.Data data = 2;</code>
   */
  public vn.zalopay.ducnm8.grpc.HistoryResponse.DataOrBuilder getDataOrBuilder() {
    return getData();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (error_ != null) {
      output.writeMessage(1, getError());
    }
    if (data_ != null) {
      output.writeMessage(2, getData());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getError());
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vn.zalopay.ducnm8.grpc.HistoryResponse)) {
      return super.equals(obj);
    }
    vn.zalopay.ducnm8.grpc.HistoryResponse other = (vn.zalopay.ducnm8.grpc.HistoryResponse) obj;

    boolean result = true;
    result = result && (hasError() == other.hasError());
    if (hasError()) {
      result = result && getError()
          .equals(other.getError());
    }
    result = result && (hasData() == other.hasData());
    if (hasData()) {
      result = result && getData()
          .equals(other.getData());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vn.zalopay.ducnm8.grpc.HistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vn.zalopay.ducnm8.grpc.HistoryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fintech.HistoryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintech.HistoryResponse)
      vn.zalopay.ducnm8.grpc.HistoryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vn.zalopay.ducnm8.grpc.HistoryResponse.class, vn.zalopay.ducnm8.grpc.HistoryResponse.Builder.class);
    }

    // Construct using vn.zalopay.ducnm8.grpc.HistoryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_HistoryResponse_descriptor;
    }

    public vn.zalopay.ducnm8.grpc.HistoryResponse getDefaultInstanceForType() {
      return vn.zalopay.ducnm8.grpc.HistoryResponse.getDefaultInstance();
    }

    public vn.zalopay.ducnm8.grpc.HistoryResponse build() {
      vn.zalopay.ducnm8.grpc.HistoryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public vn.zalopay.ducnm8.grpc.HistoryResponse buildPartial() {
      vn.zalopay.ducnm8.grpc.HistoryResponse result = new vn.zalopay.ducnm8.grpc.HistoryResponse(this);
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vn.zalopay.ducnm8.grpc.HistoryResponse) {
        return mergeFrom((vn.zalopay.ducnm8.grpc.HistoryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vn.zalopay.ducnm8.grpc.HistoryResponse other) {
      if (other == vn.zalopay.ducnm8.grpc.HistoryResponse.getDefaultInstance()) return this;
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      vn.zalopay.ducnm8.grpc.HistoryResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (vn.zalopay.ducnm8.grpc.HistoryResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private vn.zalopay.ducnm8.grpc.Error error_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        vn.zalopay.ducnm8.grpc.Error, vn.zalopay.ducnm8.grpc.Error.Builder, vn.zalopay.ducnm8.grpc.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public vn.zalopay.ducnm8.grpc.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? vn.zalopay.ducnm8.grpc.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public Builder setError(vn.zalopay.ducnm8.grpc.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public Builder setError(
        vn.zalopay.ducnm8.grpc.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public Builder mergeError(vn.zalopay.ducnm8.grpc.Error value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            vn.zalopay.ducnm8.grpc.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public vn.zalopay.ducnm8.grpc.Error.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public vn.zalopay.ducnm8.grpc.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            vn.zalopay.ducnm8.grpc.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vn.zalopay.ducnm8.grpc.Error, vn.zalopay.ducnm8.grpc.Error.Builder, vn.zalopay.ducnm8.grpc.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vn.zalopay.ducnm8.grpc.Error, vn.zalopay.ducnm8.grpc.Error.Builder, vn.zalopay.ducnm8.grpc.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private vn.zalopay.ducnm8.grpc.HistoryResponse.Data data_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        vn.zalopay.ducnm8.grpc.HistoryResponse.Data, vn.zalopay.ducnm8.grpc.HistoryResponse.Data.Builder, vn.zalopay.ducnm8.grpc.HistoryResponse.DataOrBuilder> dataBuilder_;
    /**
     * <code>.fintech.HistoryResponse.Data data = 2;</code>
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <code>.fintech.HistoryResponse.Data data = 2;</code>
     */
    public vn.zalopay.ducnm8.grpc.HistoryResponse.Data getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? vn.zalopay.ducnm8.grpc.HistoryResponse.Data.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintech.HistoryResponse.Data data = 2;</code>
     */
    public Builder setData(vn.zalopay.ducnm8.grpc.HistoryResponse.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintech.HistoryResponse.Data data = 2;</code>
     */
    public Builder setData(
        vn.zalopay.ducnm8.grpc.HistoryResponse.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintech.HistoryResponse.Data data = 2;</code>
     */
    public Builder mergeData(vn.zalopay.ducnm8.grpc.HistoryResponse.Data value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            vn.zalopay.ducnm8.grpc.HistoryResponse.Data.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintech.HistoryResponse.Data data = 2;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintech.HistoryResponse.Data data = 2;</code>
     */
    public vn.zalopay.ducnm8.grpc.HistoryResponse.Data.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintech.HistoryResponse.Data data = 2;</code>
     */
    public vn.zalopay.ducnm8.grpc.HistoryResponse.DataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            vn.zalopay.ducnm8.grpc.HistoryResponse.Data.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.fintech.HistoryResponse.Data data = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vn.zalopay.ducnm8.grpc.HistoryResponse.Data, vn.zalopay.ducnm8.grpc.HistoryResponse.Data.Builder, vn.zalopay.ducnm8.grpc.HistoryResponse.DataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vn.zalopay.ducnm8.grpc.HistoryResponse.Data, vn.zalopay.ducnm8.grpc.HistoryResponse.Data.Builder, vn.zalopay.ducnm8.grpc.HistoryResponse.DataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintech.HistoryResponse)
  }

  // @@protoc_insertion_point(class_scope:fintech.HistoryResponse)
  private static final vn.zalopay.ducnm8.grpc.HistoryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vn.zalopay.ducnm8.grpc.HistoryResponse();
  }

  public static vn.zalopay.ducnm8.grpc.HistoryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HistoryResponse>
      PARSER = new com.google.protobuf.AbstractParser<HistoryResponse>() {
    public HistoryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new HistoryResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HistoryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HistoryResponse> getParserForType() {
    return PARSER;
  }

  public vn.zalopay.ducnm8.grpc.HistoryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

