// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintech.proto

package vn.zalopay.ducnm8.grpc;

public interface NotificationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fintech.NotificationRequest)
    com.google.protobuf.MessageOrBuilder {
}
