// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintech.proto

package vn.zalopay.ducnm8.grpc;

public interface NotificationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fintech.NotificationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.fintech.Error error = 1;</code>
   */
  boolean hasError();
  /**
   * <code>.fintech.Error error = 1;</code>
   */
  vn.zalopay.ducnm8.grpc.Error getError();
  /**
   * <code>.fintech.Error error = 1;</code>
   */
  vn.zalopay.ducnm8.grpc.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>.fintech.NotificationResponse.Data data = 2;</code>
   */
  boolean hasData();
  /**
   * <code>.fintech.NotificationResponse.Data data = 2;</code>
   */
  vn.zalopay.ducnm8.grpc.NotificationResponse.Data getData();
  /**
   * <code>.fintech.NotificationResponse.Data data = 2;</code>
   */
  vn.zalopay.ducnm8.grpc.NotificationResponse.DataOrBuilder getDataOrBuilder();
}
