// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintech.proto

package vn.zalopay.ducnm8.grpc;

/**
 * Protobuf type {@code fintech.TransferResponse}
 */
public  final class TransferResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintech.TransferResponse)
    TransferResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransferResponse.newBuilder() to construct.
  private TransferResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransferResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransferResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            vn.zalopay.ducnm8.grpc.Error.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(vn.zalopay.ducnm8.grpc.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            vn.zalopay.ducnm8.grpc.TransferResponse.Data.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(vn.zalopay.ducnm8.grpc.TransferResponse.Data.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_TransferResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_TransferResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vn.zalopay.ducnm8.grpc.TransferResponse.class, vn.zalopay.ducnm8.grpc.TransferResponse.Builder.class);
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fintech.TransferResponse.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * After transfer succeed, return a history of that transfer
     * Need password from request header for authorization
     * </pre>
     *
     * <code>.fintech.HistoryItem history_item = 1;</code>
     */
    boolean hasHistoryItem();
    /**
     * <pre>
     * After transfer succeed, return a history of that transfer
     * Need password from request header for authorization
     * </pre>
     *
     * <code>.fintech.HistoryItem history_item = 1;</code>
     */
    vn.zalopay.ducnm8.grpc.HistoryItem getHistoryItem();
    /**
     * <pre>
     * After transfer succeed, return a history of that transfer
     * Need password from request header for authorization
     * </pre>
     *
     * <code>.fintech.HistoryItem history_item = 1;</code>
     */
    vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder getHistoryItemOrBuilder();
  }
  /**
   * Protobuf type {@code fintech.TransferResponse.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fintech.TransferResponse.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              vn.zalopay.ducnm8.grpc.HistoryItem.Builder subBuilder = null;
              if (historyItem_ != null) {
                subBuilder = historyItem_.toBuilder();
              }
              historyItem_ = input.readMessage(vn.zalopay.ducnm8.grpc.HistoryItem.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(historyItem_);
                historyItem_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_TransferResponse_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_TransferResponse_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vn.zalopay.ducnm8.grpc.TransferResponse.Data.class, vn.zalopay.ducnm8.grpc.TransferResponse.Data.Builder.class);
    }

    public static final int HISTORY_ITEM_FIELD_NUMBER = 1;
    private vn.zalopay.ducnm8.grpc.HistoryItem historyItem_;
    /**
     * <pre>
     * After transfer succeed, return a history of that transfer
     * Need password from request header for authorization
     * </pre>
     *
     * <code>.fintech.HistoryItem history_item = 1;</code>
     */
    public boolean hasHistoryItem() {
      return historyItem_ != null;
    }
    /**
     * <pre>
     * After transfer succeed, return a history of that transfer
     * Need password from request header for authorization
     * </pre>
     *
     * <code>.fintech.HistoryItem history_item = 1;</code>
     */
    public vn.zalopay.ducnm8.grpc.HistoryItem getHistoryItem() {
      return historyItem_ == null ? vn.zalopay.ducnm8.grpc.HistoryItem.getDefaultInstance() : historyItem_;
    }
    /**
     * <pre>
     * After transfer succeed, return a history of that transfer
     * Need password from request header for authorization
     * </pre>
     *
     * <code>.fintech.HistoryItem history_item = 1;</code>
     */
    public vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder getHistoryItemOrBuilder() {
      return getHistoryItem();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (historyItem_ != null) {
        output.writeMessage(1, getHistoryItem());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (historyItem_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHistoryItem());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vn.zalopay.ducnm8.grpc.TransferResponse.Data)) {
        return super.equals(obj);
      }
      vn.zalopay.ducnm8.grpc.TransferResponse.Data other = (vn.zalopay.ducnm8.grpc.TransferResponse.Data) obj;

      boolean result = true;
      result = result && (hasHistoryItem() == other.hasHistoryItem());
      if (hasHistoryItem()) {
        result = result && getHistoryItem()
            .equals(other.getHistoryItem());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHistoryItem()) {
        hash = (37 * hash) + HISTORY_ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getHistoryItem().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vn.zalopay.ducnm8.grpc.TransferResponse.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fintech.TransferResponse.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fintech.TransferResponse.Data)
        vn.zalopay.ducnm8.grpc.TransferResponse.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_TransferResponse_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_TransferResponse_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vn.zalopay.ducnm8.grpc.TransferResponse.Data.class, vn.zalopay.ducnm8.grpc.TransferResponse.Data.Builder.class);
      }

      // Construct using vn.zalopay.ducnm8.grpc.TransferResponse.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (historyItemBuilder_ == null) {
          historyItem_ = null;
        } else {
          historyItem_ = null;
          historyItemBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_TransferResponse_Data_descriptor;
      }

      public vn.zalopay.ducnm8.grpc.TransferResponse.Data getDefaultInstanceForType() {
        return vn.zalopay.ducnm8.grpc.TransferResponse.Data.getDefaultInstance();
      }

      public vn.zalopay.ducnm8.grpc.TransferResponse.Data build() {
        vn.zalopay.ducnm8.grpc.TransferResponse.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public vn.zalopay.ducnm8.grpc.TransferResponse.Data buildPartial() {
        vn.zalopay.ducnm8.grpc.TransferResponse.Data result = new vn.zalopay.ducnm8.grpc.TransferResponse.Data(this);
        if (historyItemBuilder_ == null) {
          result.historyItem_ = historyItem_;
        } else {
          result.historyItem_ = historyItemBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vn.zalopay.ducnm8.grpc.TransferResponse.Data) {
          return mergeFrom((vn.zalopay.ducnm8.grpc.TransferResponse.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vn.zalopay.ducnm8.grpc.TransferResponse.Data other) {
        if (other == vn.zalopay.ducnm8.grpc.TransferResponse.Data.getDefaultInstance()) return this;
        if (other.hasHistoryItem()) {
          mergeHistoryItem(other.getHistoryItem());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vn.zalopay.ducnm8.grpc.TransferResponse.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vn.zalopay.ducnm8.grpc.TransferResponse.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private vn.zalopay.ducnm8.grpc.HistoryItem historyItem_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          vn.zalopay.ducnm8.grpc.HistoryItem, vn.zalopay.ducnm8.grpc.HistoryItem.Builder, vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder> historyItemBuilder_;
      /**
       * <pre>
       * After transfer succeed, return a history of that transfer
       * Need password from request header for authorization
       * </pre>
       *
       * <code>.fintech.HistoryItem history_item = 1;</code>
       */
      public boolean hasHistoryItem() {
        return historyItemBuilder_ != null || historyItem_ != null;
      }
      /**
       * <pre>
       * After transfer succeed, return a history of that transfer
       * Need password from request header for authorization
       * </pre>
       *
       * <code>.fintech.HistoryItem history_item = 1;</code>
       */
      public vn.zalopay.ducnm8.grpc.HistoryItem getHistoryItem() {
        if (historyItemBuilder_ == null) {
          return historyItem_ == null ? vn.zalopay.ducnm8.grpc.HistoryItem.getDefaultInstance() : historyItem_;
        } else {
          return historyItemBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * After transfer succeed, return a history of that transfer
       * Need password from request header for authorization
       * </pre>
       *
       * <code>.fintech.HistoryItem history_item = 1;</code>
       */
      public Builder setHistoryItem(vn.zalopay.ducnm8.grpc.HistoryItem value) {
        if (historyItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          historyItem_ = value;
          onChanged();
        } else {
          historyItemBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * After transfer succeed, return a history of that transfer
       * Need password from request header for authorization
       * </pre>
       *
       * <code>.fintech.HistoryItem history_item = 1;</code>
       */
      public Builder setHistoryItem(
          vn.zalopay.ducnm8.grpc.HistoryItem.Builder builderForValue) {
        if (historyItemBuilder_ == null) {
          historyItem_ = builderForValue.build();
          onChanged();
        } else {
          historyItemBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * After transfer succeed, return a history of that transfer
       * Need password from request header for authorization
       * </pre>
       *
       * <code>.fintech.HistoryItem history_item = 1;</code>
       */
      public Builder mergeHistoryItem(vn.zalopay.ducnm8.grpc.HistoryItem value) {
        if (historyItemBuilder_ == null) {
          if (historyItem_ != null) {
            historyItem_ =
              vn.zalopay.ducnm8.grpc.HistoryItem.newBuilder(historyItem_).mergeFrom(value).buildPartial();
          } else {
            historyItem_ = value;
          }
          onChanged();
        } else {
          historyItemBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * After transfer succeed, return a history of that transfer
       * Need password from request header for authorization
       * </pre>
       *
       * <code>.fintech.HistoryItem history_item = 1;</code>
       */
      public Builder clearHistoryItem() {
        if (historyItemBuilder_ == null) {
          historyItem_ = null;
          onChanged();
        } else {
          historyItem_ = null;
          historyItemBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * After transfer succeed, return a history of that transfer
       * Need password from request header for authorization
       * </pre>
       *
       * <code>.fintech.HistoryItem history_item = 1;</code>
       */
      public vn.zalopay.ducnm8.grpc.HistoryItem.Builder getHistoryItemBuilder() {
        
        onChanged();
        return getHistoryItemFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * After transfer succeed, return a history of that transfer
       * Need password from request header for authorization
       * </pre>
       *
       * <code>.fintech.HistoryItem history_item = 1;</code>
       */
      public vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder getHistoryItemOrBuilder() {
        if (historyItemBuilder_ != null) {
          return historyItemBuilder_.getMessageOrBuilder();
        } else {
          return historyItem_ == null ?
              vn.zalopay.ducnm8.grpc.HistoryItem.getDefaultInstance() : historyItem_;
        }
      }
      /**
       * <pre>
       * After transfer succeed, return a history of that transfer
       * Need password from request header for authorization
       * </pre>
       *
       * <code>.fintech.HistoryItem history_item = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          vn.zalopay.ducnm8.grpc.HistoryItem, vn.zalopay.ducnm8.grpc.HistoryItem.Builder, vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder> 
          getHistoryItemFieldBuilder() {
        if (historyItemBuilder_ == null) {
          historyItemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              vn.zalopay.ducnm8.grpc.HistoryItem, vn.zalopay.ducnm8.grpc.HistoryItem.Builder, vn.zalopay.ducnm8.grpc.HistoryItemOrBuilder>(
                  getHistoryItem(),
                  getParentForChildren(),
                  isClean());
          historyItem_ = null;
        }
        return historyItemBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fintech.TransferResponse.Data)
    }

    // @@protoc_insertion_point(class_scope:fintech.TransferResponse.Data)
    private static final vn.zalopay.ducnm8.grpc.TransferResponse.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vn.zalopay.ducnm8.grpc.TransferResponse.Data();
    }

    public static vn.zalopay.ducnm8.grpc.TransferResponse.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    public vn.zalopay.ducnm8.grpc.TransferResponse.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ERROR_FIELD_NUMBER = 1;
  private vn.zalopay.ducnm8.grpc.Error error_;
  /**
   * <code>.fintech.Error error = 1;</code>
   */
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.fintech.Error error = 1;</code>
   */
  public vn.zalopay.ducnm8.grpc.Error getError() {
    return error_ == null ? vn.zalopay.ducnm8.grpc.Error.getDefaultInstance() : error_;
  }
  /**
   * <code>.fintech.Error error = 1;</code>
   */
  public vn.zalopay.ducnm8.grpc.ErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private vn.zalopay.ducnm8.grpc.TransferResponse.Data data_;
  /**
   * <code>.fintech.TransferResponse.Data data = 2;</code>
   */
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.fintech.TransferResponse.Data data = 2;</code>
   */
  public vn.zalopay.ducnm8.grpc.TransferResponse.Data getData() {
    return data_ == null ? vn.zalopay.ducnm8.grpc.TransferResponse.Data.getDefaultInstance() : data_;
  }
  /**
   * <code>.fintech.TransferResponse.Data data = 2;</code>
   */
  public vn.zalopay.ducnm8.grpc.TransferResponse.DataOrBuilder getDataOrBuilder() {
    return getData();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (error_ != null) {
      output.writeMessage(1, getError());
    }
    if (data_ != null) {
      output.writeMessage(2, getData());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getError());
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vn.zalopay.ducnm8.grpc.TransferResponse)) {
      return super.equals(obj);
    }
    vn.zalopay.ducnm8.grpc.TransferResponse other = (vn.zalopay.ducnm8.grpc.TransferResponse) obj;

    boolean result = true;
    result = result && (hasError() == other.hasError());
    if (hasError()) {
      result = result && getError()
          .equals(other.getError());
    }
    result = result && (hasData() == other.hasData());
    if (hasData()) {
      result = result && getData()
          .equals(other.getData());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vn.zalopay.ducnm8.grpc.TransferResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vn.zalopay.ducnm8.grpc.TransferResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vn.zalopay.ducnm8.grpc.TransferResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fintech.TransferResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintech.TransferResponse)
      vn.zalopay.ducnm8.grpc.TransferResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_TransferResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_TransferResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vn.zalopay.ducnm8.grpc.TransferResponse.class, vn.zalopay.ducnm8.grpc.TransferResponse.Builder.class);
    }

    // Construct using vn.zalopay.ducnm8.grpc.TransferResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vn.zalopay.ducnm8.grpc.FinTechProto.internal_static_fintech_TransferResponse_descriptor;
    }

    public vn.zalopay.ducnm8.grpc.TransferResponse getDefaultInstanceForType() {
      return vn.zalopay.ducnm8.grpc.TransferResponse.getDefaultInstance();
    }

    public vn.zalopay.ducnm8.grpc.TransferResponse build() {
      vn.zalopay.ducnm8.grpc.TransferResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public vn.zalopay.ducnm8.grpc.TransferResponse buildPartial() {
      vn.zalopay.ducnm8.grpc.TransferResponse result = new vn.zalopay.ducnm8.grpc.TransferResponse(this);
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vn.zalopay.ducnm8.grpc.TransferResponse) {
        return mergeFrom((vn.zalopay.ducnm8.grpc.TransferResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vn.zalopay.ducnm8.grpc.TransferResponse other) {
      if (other == vn.zalopay.ducnm8.grpc.TransferResponse.getDefaultInstance()) return this;
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      vn.zalopay.ducnm8.grpc.TransferResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (vn.zalopay.ducnm8.grpc.TransferResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private vn.zalopay.ducnm8.grpc.Error error_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        vn.zalopay.ducnm8.grpc.Error, vn.zalopay.ducnm8.grpc.Error.Builder, vn.zalopay.ducnm8.grpc.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public vn.zalopay.ducnm8.grpc.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? vn.zalopay.ducnm8.grpc.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public Builder setError(vn.zalopay.ducnm8.grpc.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public Builder setError(
        vn.zalopay.ducnm8.grpc.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public Builder mergeError(vn.zalopay.ducnm8.grpc.Error value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            vn.zalopay.ducnm8.grpc.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public vn.zalopay.ducnm8.grpc.Error.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    public vn.zalopay.ducnm8.grpc.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            vn.zalopay.ducnm8.grpc.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.fintech.Error error = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vn.zalopay.ducnm8.grpc.Error, vn.zalopay.ducnm8.grpc.Error.Builder, vn.zalopay.ducnm8.grpc.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vn.zalopay.ducnm8.grpc.Error, vn.zalopay.ducnm8.grpc.Error.Builder, vn.zalopay.ducnm8.grpc.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private vn.zalopay.ducnm8.grpc.TransferResponse.Data data_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        vn.zalopay.ducnm8.grpc.TransferResponse.Data, vn.zalopay.ducnm8.grpc.TransferResponse.Data.Builder, vn.zalopay.ducnm8.grpc.TransferResponse.DataOrBuilder> dataBuilder_;
    /**
     * <code>.fintech.TransferResponse.Data data = 2;</code>
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <code>.fintech.TransferResponse.Data data = 2;</code>
     */
    public vn.zalopay.ducnm8.grpc.TransferResponse.Data getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? vn.zalopay.ducnm8.grpc.TransferResponse.Data.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintech.TransferResponse.Data data = 2;</code>
     */
    public Builder setData(vn.zalopay.ducnm8.grpc.TransferResponse.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintech.TransferResponse.Data data = 2;</code>
     */
    public Builder setData(
        vn.zalopay.ducnm8.grpc.TransferResponse.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintech.TransferResponse.Data data = 2;</code>
     */
    public Builder mergeData(vn.zalopay.ducnm8.grpc.TransferResponse.Data value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            vn.zalopay.ducnm8.grpc.TransferResponse.Data.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintech.TransferResponse.Data data = 2;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintech.TransferResponse.Data data = 2;</code>
     */
    public vn.zalopay.ducnm8.grpc.TransferResponse.Data.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintech.TransferResponse.Data data = 2;</code>
     */
    public vn.zalopay.ducnm8.grpc.TransferResponse.DataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            vn.zalopay.ducnm8.grpc.TransferResponse.Data.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.fintech.TransferResponse.Data data = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vn.zalopay.ducnm8.grpc.TransferResponse.Data, vn.zalopay.ducnm8.grpc.TransferResponse.Data.Builder, vn.zalopay.ducnm8.grpc.TransferResponse.DataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vn.zalopay.ducnm8.grpc.TransferResponse.Data, vn.zalopay.ducnm8.grpc.TransferResponse.Data.Builder, vn.zalopay.ducnm8.grpc.TransferResponse.DataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintech.TransferResponse)
  }

  // @@protoc_insertion_point(class_scope:fintech.TransferResponse)
  private static final vn.zalopay.ducnm8.grpc.TransferResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vn.zalopay.ducnm8.grpc.TransferResponse();
  }

  public static vn.zalopay.ducnm8.grpc.TransferResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransferResponse>
      PARSER = new com.google.protobuf.AbstractParser<TransferResponse>() {
    public TransferResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransferResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransferResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransferResponse> getParserForType() {
    return PARSER;
  }

  public vn.zalopay.ducnm8.grpc.TransferResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

