@startuml transfer
    actor User1
    actor User2
    User1 -> "backend" : transfer(sender_id, receiver_id, amount, password)
    "backend" -> "MySQL" : getPassword(user_id)
    "MySQL" -> "backend" : return password
    "backend" -> "backend" : check if password is correct
    alt (password is not correct)
    "backend" -> User1 : Transfer failed, wrong password
    else (password is correct)

    "backend" -> "MySQL" : getBalance(sender_id)
    "MySQL" -> "backend" : return balance
    "backend" -> "backend" : check if balance > amount
    alt (balance < amount)
    "backend" -> User1 : does not save enough money
   
    else (balance >= amount)
    "backend" -> "MySQL" : minusBalance(sender_id, amount)
    "MySQL" -> "backend" : OK
    "backend" -> "MySQL" : plusBalance(receiver_id, amount)
    "MySQL" -> "backend" : OK
    "backend" -> "MySQL" : create transfer certificate
    "MySQL" -> "backend" : OK
    "backend" -> "MySQL" : create history for sender
    "MySQL" -> "backend" : OK
    "backend" -> "MySQL" : create history for receiver
    "MySQL" -> "backend" : OK
    "backend" -> User1 : return OK + history
    "backend" -> User2 : return notification
    end
@enduml