-- MySQL Script generated by MySQL Workbench
-- Thứ hai, 28 Tháng 9 Năm 2020 14:17:52 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema snailproject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `snailproject` ;

-- -----------------------------------------------------
-- Schema snailproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `snailproject` DEFAULT CHARACTER SET utf8 ;
USE `snailproject` ;

-- -----------------------------------------------------
-- Table `snailproject`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`user` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `full_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(160) CHARACTER SET 'utf8' NOT NULL,
  `sex` BIT(1) NULL DEFAULT NULL,
  `birth_day` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `snailproject`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`chat` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`chat` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `mode` INT(11) NOT NULL,
  `user_send_id` BIGINT(20) NOT NULL,
  `user_receive_id` BIGINT(20) NOT NULL,
  `content` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sent_time` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_chat_1_idx` (`user_send_id` ASC),
  INDEX `fk_chat_2_idx` (`user_receive_id` ASC),
  CONSTRAINT `fk_chat_1`
    FOREIGN KEY (`user_send_id`)
    REFERENCES `snailproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_2`
    FOREIGN KEY (`user_receive_id`)
    REFERENCES `snailproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `snailproject`.`transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`transfer` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`transfer` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sender_id` BIGINT(20) NOT NULL,
  `receiver_id` BIGINT(20) NOT NULL,
  `amount` BIGINT(20) NOT NULL,
  `message` VARCHAR(160) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `transfer_time` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index3` (`sender_id` ASC),
  INDEX `fk_transfer_2_idx` (`receiver_id` ASC),
  CONSTRAINT `fk_transfer_1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `snailproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `snailproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `snailproject`.`transfer_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`transfer_history` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`transfer_history` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `transfer_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `transfer_type` INT(11) NOT NULL,
  `balance` BIGINT(20) NOT NULL,
  `unread` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index3` (`transfer_id` ASC),
  INDEX `fk_transfer_history_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_transfer_history_1`
    FOREIGN KEY (`transfer_id`)
    REFERENCES `snailproject`.`transfer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_history_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `snailproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
