-- MySQL Script generated by MySQL Workbench
-- Thứ tư, 30 Tháng 9 Năm 2020 15:38:24 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema snailproject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `snailproject` ;

-- -----------------------------------------------------
-- Schema snailproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `snailproject` DEFAULT CHARACTER SET utf8 ;
USE `snailproject` ;

-- -----------------------------------------------------
-- Table `snailproject`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`account` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`account` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `full_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(160) CHARACTER SET 'utf8' NOT NULL,
  `balance` BIGINT(20) NOT NULL,
  `last_time_update_balance` BIGINT(20) NULL DEFAULT NULL,
  `unread_notification` INT(11) NULL DEFAULT NULL,
  `sex` BIT(1) NULL DEFAULT NULL,
  `birth_day` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `snailproject`.`conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`conversation` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`conversation` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `last_time_chat` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `snailproject`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`chat` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`chat` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `conversation_id` BIGINT(20) NOT NULL,
  `mode` INT(11) NOT NULL,
  `content` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sent_direction` INT(11) NOT NULL,
  `sent_time` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_chat_1_idx` (`conversation_id` ASC),
  CONSTRAINT `fk_chat_1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `snailproject`.`conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `snailproject`.`conversation_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`conversation_member` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`conversation_member` (
  `id` BIGINT(20) NOT NULL,
  `conversation_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `unread_chat` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index3` (`conversation_id` ASC),
  INDEX `fk_conversation_member_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_conversation_member_1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `snailproject`.`conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversation_member_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `snailproject`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `snailproject`.`friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`friend` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`friend` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `mode` INT(11) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `user_friend_id` BIGINT(20) NOT NULL,
  `friend_request_sent_time` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index3` (`user_id` ASC),
  INDEX `index4` (`user_friend_id` ASC),
  CONSTRAINT `fk_friend_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `snailproject`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_2`
    FOREIGN KEY (`user_friend_id`)
    REFERENCES `snailproject`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `snailproject`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`notification` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`notification` (
  `id` BIGINT(20) NOT NULL,
  `mode` INT(11) NOT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  `partner_id` BIGINT(20) NULL DEFAULT NULL,
  `amount` BIGINT(20) NULL DEFAULT NULL,
  `message` VARCHAR(160) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `unread` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index3` (`user_id` ASC),
  INDEX `fk_notification_2_idx` (`partner_id` ASC),
  CONSTRAINT `fk_notification_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `snailproject`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_2`
    FOREIGN KEY (`partner_id`)
    REFERENCES `snailproject`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `snailproject`.`transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`transfer` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`transfer` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sender_id` BIGINT(20) NOT NULL,
  `receiver_id` BIGINT(20) NOT NULL,
  `amount` BIGINT(20) NOT NULL,
  `message` VARCHAR(160) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `transfer_time` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index3` (`sender_id` ASC),
  INDEX `fk_transfer_2_idx` (`receiver_id` ASC),
  CONSTRAINT `fk_transfer_1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `snailproject`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `snailproject`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `snailproject`.`transfer_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snailproject`.`transfer_history` ;

CREATE TABLE IF NOT EXISTS `snailproject`.`transfer_history` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `transfer_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `transfer_type` INT(11) NOT NULL,
  `balance` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `index3` (`transfer_id` ASC),
  INDEX `fk_transfer_history_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_transfer_history_1`
    FOREIGN KEY (`transfer_id`)
    REFERENCES `snailproject`.`transfer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_history_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `snailproject`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
